package com.advisor.controller;

import com.advisor.entity.User;
import com.advisor.entity.UserCareerPath;
import com.advisor.repository.UserRepository;
import com.advisor.service.UserCareerPathService;
import org.springframework.security.core.Authentication;
import com.advisor.repository.CareerPathRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import jakarta.annotation.PostConstruct;

import java.util.List;
import java.util.Map;

import com.advisor.entity.CareerPath; // Re-adding this import as it was removed

@RestController
@RequestMapping("/api/career-paths")
public class CareerPathsController {

    private final CareerPathRepository careerPathRepository;
    private final UserCareerPathService userCareerPathService;
    private final UserRepository userRepository;

    public CareerPathsController(CareerPathRepository careerPathRepository, 
                               UserCareerPathService userCareerPathService,
                               UserRepository userRepository) {
        this.careerPathRepository = careerPathRepository;
        this.userCareerPathService = userCareerPathService;
        this.userRepository = userRepository;
    }

    @PostConstruct
    public void init() {
        if (careerPathRepository.count() == 0) {
            careerPathRepository.saveAll(List.of(
                new CareerPath(
                    null, // ID generated by UUID
                    "Frontend Developer",
                    "Build rich, accessible UIs with modern frameworks like React.",
                    "Mid-Level",
                    "Technology",
                    "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400",
                    "$70,000 - $110,000",
                    "18%",
                    87,
                    List.of("JavaScript", "React", "HTML", "CSS", "Accessibility"),
                    List.of(
                        Map.of("level", "Junior", "salary", "$60k-$80k"),
                        Map.of("level", "Mid", "salary", "$80k-$110k"),
                        Map.of("level", "Senior", "salary", "$110k-$150k")
                    )
                ),
                new CareerPath(
                    null,
                    "Data Scientist",
                    "Analyze data and build ML models to drive decisions.",
                    "Mid-Level",
                    "Analytics",
                    "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400",
                    "$90,000 - $140,000",
                    "22%",
                    81,
                    List.of("Python", "Statistics", "Machine Learning", "SQL"),
                    List.of(
                        Map.of("level", "Junior", "salary", "$80k-$100k"),
                        Map.of("level", "Mid", "salary", "$100k-$130k"),
                        Map.of("level", "Senior", "salary", "$130k-$170k")
                    )
                )
            ));
        }
    }

    @GetMapping
    public ResponseEntity<List<CareerPath>> list() {
        return ResponseEntity.ok(careerPathRepository.findAll());
    }

    @GetMapping("/{id}")
    public ResponseEntity<CareerPath> getById(@PathVariable String id) {
        return careerPathRepository.findById(id)
            .map(ResponseEntity::ok)
            .orElse(ResponseEntity.notFound().build());
    }

    @PostMapping
    public ResponseEntity<CareerPath> create(@RequestBody CareerPath careerPath) {
        // Ensure ID is null so it gets generated
        careerPath.setId(null);
        return ResponseEntity.ok(careerPathRepository.save(careerPath));
    }

    @PutMapping("/{id}")
    public ResponseEntity<CareerPath> update(@PathVariable String id, @RequestBody CareerPath careerPath) {
        if (!careerPathRepository.existsById(id)) {
            return ResponseEntity.notFound().build();
        }
        careerPath.setId(id);
        return ResponseEntity.ok(careerPathRepository.save(careerPath));
    }

    @PostMapping("/{id}/apply")
    public ResponseEntity<?> apply(@PathVariable String id, Authentication auth) {
        User u = userRepository.findByEmail(auth.getName()).orElseThrow();
        try {
            UserCareerPath application = userCareerPathService.applyForCareerPath(u, id);
            return ResponseEntity.ok(application);
        } catch (RuntimeException e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }

    @GetMapping("/my-applications")
    public ResponseEntity<List<UserCareerPath>> myApplications(Authentication auth) {
        User u = userRepository.findByEmail(auth.getName()).orElseThrow();
        return ResponseEntity.ok(userCareerPathService.getUserApplications(u));
    }

    @GetMapping("/my-saved")
    public ResponseEntity<List<com.advisor.entity.UserSavedCareerPath>> mySaved(Authentication auth) {
        User u = userRepository.findByEmail(auth.getName()).orElseThrow();
        return ResponseEntity.ok(userCareerPathService.getUserSavedCareers(u));
    }

    @GetMapping("/user/{userId}/applications")
    public ResponseEntity<List<UserCareerPath>> userApplications(@PathVariable String userId, Authentication auth) {
        User requester = userRepository.findByEmail(auth.getName()).orElseThrow();
        if (!requester.getId().equals(userId)) {
            return ResponseEntity.status(403).build();
        }
        User u = userRepository.findById(userId).orElseThrow();
        return ResponseEntity.ok(userCareerPathService.getUserApplications(u));
    }

    @PostMapping("/{id}/save")
    public ResponseEntity<com.advisor.entity.UserSavedCareerPath> save(@PathVariable String id, Authentication auth) {
        User u = userRepository.findByEmail(auth.getName()).orElseThrow();
        return ResponseEntity.ok(userCareerPathService.saveCareerPath(u, id));
    }

    @DeleteMapping("/{id}/save")
    public ResponseEntity<Void> unsave(@PathVariable String id, Authentication auth) {
        User u = userRepository.findByEmail(auth.getName()).orElseThrow();
        userCareerPathService.unsaveCareerPath(u, id);
        return ResponseEntity.ok().build();
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable String id) {
        if (!careerPathRepository.existsById(id)) {
            return ResponseEntity.notFound().build();
        }
        careerPathRepository.deleteById(id);
        return ResponseEntity.ok().build();
    }
}
